version: 2

models:
  - name: stg_transactions_enriched
    columns:
      - name: value
        data_tests:
          - assert_value_amount_positive:
              field: block_number
  - name: stg_transactions
    description: > 
      this is gathering all the data from etherum blocktrain
    columns:
      - name: hash
        data_tests:
          - unique
          - not_null
  - name: stablecoin_activity_per_day
    latest_version: 1
    config:
      contract:
        enforced: true
    columns:
      - name: date
        data_type: date
        description: ""

      - name: token_address
        data_type: varchar
        description: ""

      - name: type
        data_type: varchar
        description: ""

      - name: symbol
        data_type: varchar
        description: ""

      - name: total_usd_value
        data_type: float
        description: ""
    versions:
    
      - v: 1
        deprecation_date: 2026-06-04
        # Matches what's above -- nothing more needed
    
      - v: 2
        # Removed a column -- this is the breaking change!
        columns:
          # This means: use the 'columns' list from above, but exclude country_name
          - include: all
            exclude: [symbol,token_address]


unit_tests:
  - name: test_is_valid_transaction_category_breakdown
    model: stg_transactions_enriched
    overrides:
      macros:
        # unit test this model in "full refresh" mode
        is_incremental: false 
    given:
      - input: ref('stg_transactions')
        rows:
          - {receipt_contract_address: 'test'}
      - input: ref('stg_token_transfers')
        format: dict
        rows:
          - {transaction_hash: 'test'}
    expect:
      rows:
        - {transaction_category: 'contract_creation'}